-- $Id: constants.fr.lua 3151 2010-12-21 13:43:26Z trasher $
--[[
constants.fr.lua --- Traduction frFR par Trasher. Merci à KKram pour les premières traductions & Pettigrow pour ses quelques traductions.
This file defines an AceLocale table for all the various text strings needed
by AtlasLoot.  In this implementation, if a translation is missing, it will fall
back to the English translation.

The AL["text"] = true; shortcut can ONLY be used for English (the root translation).
]]





--Create the library instance
local AceLocale = LibStub:GetLibrary("AceLocale-3.0");

local AL = AceLocale:NewLocale("AtlasLoot", "frFR", false);

--Register translations
if AL then

	-- #########
	-- UI things
	-- #########
	-- AtlasLootFu 
	AL["AtlasLootFu is no longer in use.\nDelete it from your AddOns folder"] = "AtlasLootFu n'est plus utilisé. Veuillez le supprimer de votre dossier AddOns.";

	-- Options
	--AL["Options"] = true;
	AL["Load Loot Modules at Startup"] = "Charger les modules de loot au démarrage";
	AL["Minimap Button"] = "Afficher le boutton sur la mini-carte";
	AL["Show itemIDs"] = "Afficher les IDs des objets";
	AL["Show Droprates"] = "Afficher les pourcentages de drop";
	AL["Safe Chat Links"] = "Liens sûrs sur le canal";
	AL["Comparison TT"] = "Comparaison TT";
	AL["Show Comparison Tooltips"] = "Afficher les bulles d'aide comparatives";
	--AL["Supress item query text"] = true; -- à traduire
	--AL["Opaque"] = true;
	AL["Make Loot Table Opaque"] = "Fond de liste opaque";
	AL["Treat Crafted Items:"] = "Traiter les objets fabriqués :";
	AL["As Crafting Spells"] = "comme des sorts";
	AL["As Items"] = "comme des objets";
	AL["Reset"] = "Réinitialiser";
	AL["Reset Frames"] = "Réinitialiser les frames";
	--AL["Profiles"] = true;
	--AL["Item Buttons"] = true; -- à traduire
	AL["Loot Table"] = "Table de loot";

	-- Default Frame
	AL["Default Frame"] = "Frame par défaut";
	AL["Scale:"] = "Échelle :";
	AL["Alpha:"] = "Transparence :";
	--AL["Only change alpha on leave frame"] = true; -- à traduire

	-- Bindings
	--AL["Toggle AtlasLoot"] = true; -- à traduire

	-- Help
	AL["Help"] = "Aide";
	AL["AtlasLoot Help"] = "Aide AtlasLoot";
	AL["For further help, see our website and forums: "] = "Pour de l'aide complémentaire, visitez notre site web et nos forums : ";
	AL["How to open the standalone Loot Browser:"] = "Comment ouvrir le navigateur de butin indépendamment :";
	AL["If you have AtlasLootFu enabled, click the minimap button, or alternatively a button generated by a mod like Titan or FuBar.  Finally, you can type '/al' in the chat window."] = "Si AtlasLootFu est présent et installé, cliquez sur le bouton de la mini-carte ou alors sur le bouton généré par des addons tels que Titan ou Fubar. Vous pouvez également taper la commande '/al' dans la saisie de la fenêtre de discussion.";
	AL["How to view an 'unsafe' item:"] = "Comment voir un objet 'peu sûr' :";
	AL["Unsafe items have a red border around the icon and are marked because you have not seen the item since the last patch or server restart. Right-click the item, then move your mouse back over the item or click the 'Query Server' button at the bottom of the loot page."] = "Les objets peu sûrs ont une bordure rouge autour d'une icône d'un point d'interrogation car vous n'avez pas vu l'objet depuis le dernier patch ou le dernier redémarrage du serveur. Faites un Clic-Droit sur l'objet, puis survolez à nouveau l'objet avec votre souris, ou cliquez sur le bouton 'Requête serveur' en bas de la page du butin.";
	AL["How to view an item in the Dressing Room:"] = "Comment voir un objet dans la cabine d'essayage :";
	AL["Simply Ctrl+Left Click on the item.  Sometimes the dressing room window is hidden behind the Atlas or AtlasLoot windows, so if nothing seems to happen move your Atlas or AtlasLoot windows and see if anything is hidden."] = "Faites simplement la combinaison Ctrl-Clic gauche sur l'objet. Il se peut parfois que la fenêtre de la cabine d'essayage se retrouve cachée derrière la fenêtre d'Atlas ou d'AtlasLoot : si jamais rien ne semble se produire, déplacez la fenêtre d'Atlas et/ou d'AtlasLoot au cas où quelque chose soit caché derrière.";
	AL["How to link an item to someone else:"] = "Comment faire le lien d'un objet pour le montrer à quelqu'un d'autre :";
	AL["Shift+Left Click the item like you would for any other in-game item"] = "Faites la combinaison Shift+Clic-Gauche sur l'objet, exactement comme tous les autres objets du jeu.";
	AL["How to add an item to the wishlist:"] = "Comment ajouter un objet à ma liste de souhaits :";
	AL["Alt+Left Click any item to add it to the wishlist."] = "Faites la combinaison Alt+Clic-Gauche sur l'objet en question pour l'ajouter à votre liste de souhaits.";
	AL["How to delete an item from the wishlist:"] = "Comment supprimer un objet de ma liste de souhaits:";
	AL["While on the wishlist screen, just Alt+Left Click on an item to delete it."] = "Une fois sur l'écran de votre liste de souhaits, faites simplement la combinaison Alt+Clic-Gauche sur l'objet à supprimer.";
	AL["What else does the wishlist do?"] = "Qu'est-ce que la liste de souhaits peut faire de plus ?";
	AL["If you Left Click any item on the wishlist, you can jump to the loot page the item comes from.  Also, on a loot page any item already in your wishlist is marked with a yellow star."] = "Si vous faites un clic gauche sur un objet de la liste de souhaits, vous serez directement conduit sur la page du butin qui correspond. De plus, tout objet se trouvant dans votre liste sera marqué par une étoile jaune sur les pages du butin.";
	AL["HELP!! I have broken the mod somehow!"] = "AU SECOURS ! Le mod ne fonctionne plus !";
	AL["Use the reset buttons available in the options menu, or type '/al reset' in your chat window."] = "Utilisez les boutons réinitialiser présents sur le menu des options, ou tapez '/al reset' dans la saisie de votre fenêtre de discussion.";

	-- LootButtons
	-- Tooltips
	AL["ItemID:"] = "ObjetID :";
	AL["Drop Rate: "] = "Chance de tomber : ";
	--AL["DKP"] = true;
	AL["Priority:"] = "Priorité :";
	AL["Show price and slot if possible"] = "Voir le prix si possible"; -- à traduire
	--AL["Use GameTooltip"] = true; -- à traduire
	--AL["Use the standard GameTooltip instead of the custom AtlasLoot tooltip"] = true; -- à traduire
	-- Unsafe Item
	AL["Item Unavailable"] = "Objet indisponible";
	AL["|cff0070ddItemID: %d |r\nThis item is unsafe.  To view this item without the risk of disconnection, you need to have first seen it in the game world.\n\nYou can right-click to attempt to query the server.  You may be disconnected."] = "|cff0070ddItemID: %d |r\nCet objet n'est pas fiable.  Pour regarder cet objet sans risque de déconnection, vous devez déjà l'avoir vu au moins une fois dans le jeu.\n\nVous pouvez faire un Clic-Droit pour tenter d'interroger le serveur.  Vous pouvez être déconnecté.";
	-- Heriloom Config Window
	AL["Heirloom preview"] = "Aperçu des objets d'héritage";
	AL["Change level:"] = "Changer le niveau :";
	AL["Shift + Right Click to select character level"] = "Maj + Clic-Droit pour sélectionnez le niveau d'un personnage";	

	-- LootTableSort
	AL["Sort by Instance"] = "Trier par instance";
	AL["Sort loottable by Instance"] = "Trier la table de loot par instance";
	AL["Sort by Boss"] = "Trier par boss";
	AL["Sort loottable by Boss"] = "Trier la table de loot par boss";
	AL["Item Name"] = "Nom de l'objet";
	AL["Item Slot"] = "Slot de l'objet";
	AL["Item Quality"] = "Qualité de l'objet";

	-- Wishlist
	AL["Wishlist"] = "Liste de souhaits";
	AL["Wishlists"] = "Listes de souhaits";
	AL["Own"] = "Les miennes";
	AL["Other"] = "Autre";
	AL["Shared"] = "Partagée";
	AL["Wishlist name:"] = "Nom de la liste de souhaits :";
	AL["Delete"] = "Supprimer";
	AL["Share"] = "Partager";
	AL["Send Wishlist (%s) to"] = "Envoyer la liste de souhaits (%s) à";
	AL["Send"] = "Evnoyer";
	AL[" added to the WishList."] = " ajouté à la liste de souhaits";
	AL[" already in the WishList!"] = " est déjà dans la liste de souhaits !";
	AL[" deleted from the WishList."] = " à été supprimer de la liste de souhaits";
	AL["Are you sure you want to delete Wishlist |cff1eff00%s|r?"] = "Êtes-vous sûr de vouloir supprimer la liste de souhaits |cff1eff00%s|r?";
	AL["default"] = "par défaut";
	AL[" |cff999999<default>"] = " |cff999999<par défaut>";
	AL["Use as default wishlist"] = "Utiliser cette liste de souhaits par défaut";
	AL["Add Wishlist"] = "Ajouter une liste de souhaits";
	AL["Always use default Wishlist"] = "Toujours utiliser cetteliste de souhaits par défaut";
	--AL["Save wishlists at character DB"] = true; -- à traduire
	--AL["Saves the wishlists only for |cff1eff00%s-%s|r.\n Other characters cant view the wishlists, but the memory usage is reduced."] = true; -- à traduire
	--AL["Table Sort"] = true; -- à traduire
	--AL["Table Sort:"] = true; -- à traduire
	--AL["Item Sort:"] = true; -- à traduire

	-- Filter
	AL["Filter"] = "Filtre";
	AL["Select All Loot"] = "Sélectionner tous les loots";
	AL["Apply Filter:"]= "Appliquer le filtre :";
	AL["Melee weapons"] = "Armes de mêlée";
	AL["Ranged weapons"] = "Armes à distance";
	AL["Other"] = "Autre";
	AL["Itemslot"] = "Slot de l'objet";
	AL["Shift + Click on the Filter button opens the config page."] = "Maj + Clic sur le bouton Filtre ouvre la page de configuration.";

	-- Panel
	AL["Hide Panel"] = "Masquer le panneau";
	--AL["Toggle AL Panel"] = true; -- à traduire
	AL["Buttons"] = "Boutons";

	-- Buttons
	--AL["Collections"] = true;
	AL["Crafting"] = "Artisanat";
	--AL["Factions"] = true;
	AL["Load Modules"] = "Charger les modules";
	AL["PvP Rewards"] = "Récompenses JcJ";
	--AL["World Events"] = true;

	-- QuickLooks
	--AL["QuickLook"] = true;
	--AL["QuickLooks"] = true;
	AL["Number of QuickLooks:"] = "Nombre de QuickLook";
	AL["Add to QuickLooks:"] = "Ajouter à QuickLook :";
	AL["Reset Quicklooks"] = "Réinitialiser QuickLook";
	AL["Assign this loot table\n to QuickLook"] = "Assigner cette table de loot\n à QuickLook";
	AL["Show unused QuickLooks in the Panel"] = "Afficher les QuickLook inutilisé sur le panneau";
	--AL["Shows unused QuickLooks as grey buttons in the AtlasLoot Panel"] = true; -- à traduire
	-- Single options
	AL["unused"] = "inutilisé";
	AL["QuickLook name:"] = "Nom du QuickLook :";
	--AL["Use Boss name"] = true;
	--AL["Use Instance name"] = true;
	AL["Delete"] = "Supprimer";
	AL["Lock"] = "Bloquer";
	AL["Enable"] = "Activer";

	-- Query Server / Query all
	AL["Query Server"] = "Interroger le serveur";
	AL["Queries the server for all items \non this page. The items will be \nrefreshed when you next mouse \nover them."] = "Interroger le serveur pour tout les objets \nde cette page. Les objets seront rafraichis \nquand vous passerez votre souris dessus.";

	-- Atlas
	AL["Click boss name to view loot."] = "Cliquer sur le nom du boss pour voir ses loots";

	-- LootTable
	-- title
	AL["Heroic"] = "Héroïque";
	AL["25 Man"] = "25 joueurs";
	AL["25 Man Heroic"] = "25 joueurs héroïque";
	-- buttons
	AL["Show 10 Man Loot"] = "Afficher les loots Raid 10";
	AL["Show 25 Man Loot"] = "Afficher les loots Raid 25";
	AL["Show Slot"] = "Afficher le slot";
	AL["Show Price"] = "Afficher le prix";
	AL["Skill"] = "Talent";
	AL["Location"] = "Lieu";

	-- #######################################
	-- UI things END
	-- #######################################

	-- Text strings for UI objects
	--AL["AtlasLoot"] = true,
	AL["Select Loot Table"] = "Choisir une liste";
	AL["Select Sub-Table"] = "Choisir une sous-liste";
	AL["Various Locations"] = "Endroits divers";
	AL["This is a loot browser only.  To view maps as well, install either Atlas or Alphamap."] = "Ceci est un navigateur de loot. Pour afficher les cartes, veuillez installer Atlas ou Alphamap.";
	AL["Back"] = "Retour";
	AL["Level 60"] = "Niveau 60";
	AL["Level 70"] = "Niveau 70";
	AL["Level 80"] = "Niveau 80";
	AL["Level 85"] = "Niveau 85";
	AL["|cffff0000(unsafe)"] = "|cffff0000(invalide)";
	AL["Misc"] = "Divers";
	AL["Rewards"] = "Récompenses";
	AL["Choose Table ..."] = "Choisir une liste...";
	AL["Unknown"] = "Inconnu";
	AL["Reset Wishlist"] = "Réinitialiser la liste de souhaits";
	AL["Select a Loot Table..."] = "Sélectionner une table de loot...";
	AL["OR"] = "OU";
	AL["FuBar Options"] = "Options de FuBar";
	AL["Attach to Minimap"] = "Joindre à la mini-carte";
	AL["Hide FuBar Plugin"] = "Cacher le plugin FuBar";
	AL["Show FuBar Plugin"] = "Afficher le plugin FuBar";
	AL["Position:"] = "Position :";
	AL["Left"] = "Gauche";
	AL["Center"] = "Centre";
	AL["Right"] = "Droite";
	AL["Hide Text"] = "Cacher le texte";
	AL["Hide Icon"] = "Cacher l'icône";
	AL["Minimap Button Options"] = "Options du boutton de la mini-carte";
	
	-- Text for Options Panel
	AL["Atlasloot Options"] = "Options d'Atlasloot";
	AL["Default Tooltips"] = "Bulles d'aide par défault";
	AL["Lootlink Tooltips"] = "Bulles d'aide Lootlink";
	AL["|cff9d9d9dLootlink Tooltips|r"] = "|cff9d9d9dBulles d'aide Lootlink";
	AL["ItemSync Tooltips"] = "Bulles d'aide ItemSync";
	AL["|cff9d9d9dItemSync Tooltips|r"] = "|cff9d9d9dBulles d'aide ItemSync";
	AL["Use EquipCompare"] = "Utiliser EquipCompare";
	AL["|cff9d9d9dUse EquipCompare|r"] = "|cff9d9d9dUtiliser EquipCompare";
	--AL["Show itemIDs at all times"] = true; -- à traduire
	AL["Hide AtlasLoot Panel"] = "Cacher le panneau d'AtlasLoot";
	AL["Show Basic Minimap Button"] = "Afficher le bouton sur la mini-carte";
	AL["|cff9d9d9dShow Basic Minimap Button|r"] = "|cff9d9d9dAfficher le bouton sur la mini-carte|r";
	AL["Set Minimap Button Position"] = "Position du bouton sur la mini-carte";
	AL["Notify on LoD Module Load"] = "M'informer quand un module est chargé";
	AL["Loot Browser Scale: "] = "Échelle du navigateur de loot : ";
	AL["Button Position: "] = "Position du boutton :";
	AL["Button Radius: "] = "Rayon du boutton";
	AL["Done"] = "Fait";
	AL["FuBar Toggle"] = "Active ou non FuBar";
	AL["Search Result: %s"] = "Résultat(s) de la recherche : %s";
	AL["Search on"] = "Recherche activé";
	AL["All modules"] = "Tous les modules";
	AL["If checked, AtlasLoot will load and search across all the modules."] = "Si coché, AtlasLoot chargera et recherchera dans tous les modules.";
	AL["Search options"] = "Options de la recherche";
	AL["Partial matching"] = "Correspondance partielle";
	AL["If checked, AtlasLoot search item names for a partial match."] = "Si coché, AtlasLoot recherche le nom d'un objet avec une correspondance partielle.";
	AL["You don't have any module selected to search on!"] = "Vous n'avez pas sélectionné de module pour la recherche !";
	AL["Panel"] = "Panneau";

	-- Slash commands
	AL["reset"] = "Réinitialiser";
	--AL["options"] = true,
	AL["Reset complete!"] = "Réinitialisation effectuée !";

	-- AtlasLoot Panel - Search
	AL["Clear"] = "Effacer";
	AL["Last Result"] = "Dernier(s) résultat(s)";
	AL["Search"] = "Recherche";

	-- Crafting Menu
	AL["Crafting Daily Quests"] = "Artisanat des quêtes journalières";
	AL["Cooking Daily"] = "Recs. journa. de cuisine";
	AL["Fishing Daily"] = "Recs. journa. de pêche";
	AL["Jewelcrafting Daily"] = "Recs. journa. de joaillerie";
	AL["Crafted Sets"] = "Sets d'artisanat";
	AL["Crafted Epic Weapons"] = "Armes d'artisanat épiques";
	AL["Dragon's Eye"] = "Oeil de dragon";
	AL["Chimera's Eye"] = "Oeil de chimère";

	-- Sets/Collections Menu
	--AL["Sets"] = true;
	--AL["Set"] = true;
	AL["Justice Points"] = "Point de justice";
	AL["Valor Points"] = "Point de valeur";
	AL["Badge of Justice"] = "Ecusson de justice"; --should be removed
	AL["Emblem Rewards"] = "Récompenses des emblèmes"; --should be removed
	AL["Emblem of Valor"] = "Emblème de vaillance"; --should be removed
	AL["Emblem of Heroism"] = "Emblème d'héroïsme"; --should be removed
	AL["Emblem of Conquest"] = "Emblème de conquête"; --should be removed
	AL["Emblem of Triumph"] = "Emblème de triomphe"; --should be removed
	AL["Emblem of Frost"] = "Emblème de givre"; --should be removed
	AL["BoE World Epics"] = "LqE Épiques mondial";
	AL["Legendary Items"] = "Objets légendaires";
	AL["Misc Sets"] = "Sets divers";
	--AL["Tier 1/2 Set"] = true;
	--AL["Tier 1/2/3 Set"] = true;
	--AL["Tier 3 Set"] = true;
	--AL["Tier 4/5/6 Set"] = true;
	--AL["Tier 7/8 Set"] = true;
	--AL["Tier 8 Set"] = true;
	--AL["Tier 9 Set"] = true;
	--AL["Tier 10 Set"] = true;
	--AL["Tier 11 Set"] = true;
	AL["TCG Items"] = "Objets des cartes à jouer"; -- Trading Card Game Items
	AL["Transformation Items"] = "Objets de transformation";

	-- PvP Menu
	AL["Arathi Basin Sets"] = "Sets du Bassin d'Arathi";
	AL["PvP Accessories"] = "Accessoires JcJ";
	AL["PvP Armor Sets"] = "Sets d'armures JcJ";
	AL["PvP Weapons"] = "Armes JcJ";
	AL["PvP Non-Set Epics"] = "Hors sets épiques JcJ";
	AL["PvP Reputation Sets"] = "Sets réputation JcJ";
	AL["Arena PvP Weapons"] = "Armes d'arène JcJ";
	AL["PvP Misc"] = "Objets divers JcJ";
	AL["PVP Gems/Enchants/Jewelcrafting Designs"] = "Gemmes / Enchantements / Dessins de Joaillerie JcJ";
	AL["PvP Class Items"] = "Objets JcJ de classe";
	AL["NOT AVAILABLE ANYMORE"] = "N'EST PLUS DISPONIBLE";

	-- World Events
	AL["Abyssal Council"] = "Conseil abyssal";
	AL["Argent Tournament"] = "Tournoi d'Argent";
	AL["Bash'ir Landing Skyguard Raid"] = "Point d'ancrage de Bash'ir";
	AL["Brewfest"] = "La fête des Brasseurs";
	AL["Children's Week"] = "La Semaine des enfants";
	AL["Day of the Dead"] = "Jour des morts";
	AL["Elemental Invasion"] = "Invasions élémentaires";
	AL["Ethereum Prison"] = "Prison de l'Ethereum";
	AL["Feast of Winter Veil"] = "La fête du Voile d'hiver";
	AL["Gurubashi Arena Booty Run"] = "Le coffre pirate de Gurubashi";
	AL["Hallow's End"] = "La Sanssaint";
	AL["Harvest Festival"] = "La Fête des moissons";
	AL["Love is in the Air"] = "De l'amour dans l'air";
	AL["Lunar Festival"] = "La fête lunaire";
	AL["Midsummer Fire Festival"] = "Solstice d'été : la fête du Feu";
	AL["Noblegarden"] = "Le jardin des nobles";
	AL["Pilgrim's Bounty"] = "Bienfaits du pèlerin";
	--AL["Skettis"] = true,
	AL["Stranglethorn Fishing Extravaganza"] = "Concours de pêche de Strangleronce";
	AL["Elemental Unrest"] = "L'invasion des élementaires";

	-- Minimap Button
	AL["|cff1eff00Left-Click|r Browse Loot Tables"] = "|cff1eff00Clic-Gauche|r Parcours des Listes d'Objets";
	AL["|cffff0000Right-Click|r View Options"] = "|cffff0000Clic-Droit|r Affiche les Options";
	AL["|cffff0000Shift-Click|r View Options"] = "|cffff0000Shift-Clic|r Affiche les Options";
	AL["|cffccccccLeft-Click + Drag|r Move Minimap Button"] = "|cffccccccClic-Gauche + Maintenir|r Déplace le bouton sur la mini-carte";
	AL["|cffccccccRight-Click + Drag|r Move Minimap Button"] = "|cffccccccClic-Droit + Maintenir|r Déplace le bouton sur la mini-carte";

	-- Default Frame
	AL["Select Module"] = "Sélectionner un module";
	AL["Select Instance"] = "Sélectionner une instance";

	-- Wishlist
	AL["Close"] = "Fermer";
	AL["Own Wishlists"] = "Vos propres listes de souhaits";
	AL["Other Wishlists"] = "Autres listes de souhaits";
	AL["Shared Wishlists"] = "Listes de souhaits partagés";
	AL["Mark items in loot tables"] = "Marquer les objets dans les tables de butin";
	AL["Mark items from own Wishlist"] = "Marquer les objets de vos propres listes de souhaits";
	AL["Mark items from all Wishlists"] = "Marquer les objets de toutes les listes de souhaits";
	AL["Enable Wishlist Sharing"] = "Autoriser le partage des listes de souhaits";
	AL["Auto reject in combat"] = "Rejeter auto. en combat";
	AL["Edit Wishlist"] = "Modifier une liste de souhaits"
	AL["Show More Icons"] = "Afficher plus d'icône";
	AL["Edit"] = "Modifier";
	AL["Show all Wishlists"] = "Afficher toutes les listes de souhaits";
	AL["Show own Wishlists"] = "Afficher vos propres listes de souhaits";
	AL["Show shared Wishlists"] = "Afficher les listes de souhaits partagés";
	AL["You must wait "] = "Vous devez attendre";
	AL[" seconds before you can send a new Wishlist to "] = " secondes avant de pouvoir envoyer une nouvelle liste de souhaits à ";
	AL["Cancel"] = "Annuler";
	AL["Delete Wishlist %s?"] = "Supprimer la liste de souhaits %s ?";
	AL["%s sends you a Wishlist. Accept?"] = "%s souhaite vous envoyer une liste de souhaits. Acceptez-vous ?";
	AL[" tried to send you a Wishlist. Rejected because you are in combat."] = "a tenté de vous envoyer une liste de souhaits qui a été rejetée car vous êtes en combat.";
	AL[" rejects your Wishlist."] = " a rejeté votre liste de souhaits.";
	AL["You can't send Wishlists to yourself"] = "Vous ne pouvez pas envoyer de liste de souhaits à vous-même.";
	AL["Please set a default Wishlist."] = "Veuillez définir une liste de souhaits par défaut."
	AL["Set as default Wishlist"] = "Définir en tant que liste de souhaits par défaut";

	-- Misc Inventory related words
	AL["Scope"] = "Lunette de visée";
	AL["Darkmoon Faire Card"] = "Carte de la foire de Sombrelune";
	AL["Banner"] = "Etendard";
	--AL["Set"] = true,
	AL["Token"] = "Insigne";
	AL["Tokens"] = "Insignes";
	--AL["Token Hand-Ins"] = true; -- à traduire
	AL["Skinning Knife"] = "Couteau à dépecer";
	AL["Combat Pet"] = "Animal de compagnie de combat";
	AL["Fireworks"] = "Feux d'artifice";
	AL["Transformation Item"] = "Objet de transformation";
	AL["Keys"] = "Clés";

	--Extra inventory stuff
	AL["Cloak"] = "Cape";

	-- Alchemy
	AL["Battle Elixirs"] = "Elixirs de bataille";
	AL["Guardian Elixirs"] = "Elixirs du Gardien";
	--AL["Potions"] = true;
	AL["Transmutes"] = "Transmutations";
	AL["Flasks"] = "Flacons";

	-- Blacksmithing
	--AL["Cataclysm Vendor Sold Plans"] = true; --  traduire

	-- Enchanting
	AL["Enchant Boots"] = "Enchantement Bottes";
	AL["Enchant Bracer"] = "Enchantement Bracelets";
	AL["Enchant Chest"] = "Enchantement Torse";
	AL["Enchant Cloak"] = "Enchantement Cape";
	AL["Enchant Gloves"] = "Enchantement Gants";
	AL["Enchant Ring"] = "Enchantement Anneau";
	AL["Enchant Shield"] = "Enchantement Bouclier";
	AL["Enchant 2H Weapon"] = "Enchantement Arme à deux mains";
	AL["Enchant Weapon"] = "Enchantement Arme";
	--AL["Cataclysm Vendor Sold Formulas"] = true; -- à traduire

	-- Inscription
	AL["Major Glyph"] = "Glyphe majeur";
	AL["Minor Glyph"] = "Glyphe mineur";
	AL["Scrolls"] = "Parchemins";
	AL["Off-Hand Items"] = "Objets Tenu(e) en main gauche";
	AL["Reagents"] = "Réactifs";
	AL["Book of Glyph Mastery"] = "Livre de la maîtrise des glyphes";

	-- Leatherworking
	AL["Leather Armor"] = "Armure en cuir";
	AL["Mail Armor"] = "Armure en maille";
	AL["Cloaks"] = "Capes";
	AL["Item Enhancements"] = "Améliorations d'objet";
	AL["Drums, Bags and Misc."] = "Tambours, sacs et objets divers";

	-- Tailoring
	AL["Cloth Armor"] = "Armure en tissu";
	AL["Shirts"] = "Chemises";
	AL["Bags"] = "Sacs";

	-- Labels for loot descriptions
	AL["Classes:"] = "Classes :";
	AL["This Item Begins a Quest"] = "Cet objet permet de lancer une quête.";
	AL["Quest Item"] = "Objet de quête";
	AL["Old Quest Item"] = "Ancien objet de quête";
	AL["Quest Reward"] = "Récompense de quête";
	AL["Old Quest Reward"] = "Ancienne récompense de quête";
	AL["Shared"] = "Partagé";
	--AL["Unique"] = true,
	AL["Right Half"] = "Moitié droite";
	AL["Left Half"] = "Moitié gauche";
	AL["28 Slot Soul Shard"] = "28 emplacements Pierre d'âme";
	AL["20 Slot"] = "20 emplacements";
	AL["18 Slot"] = "18 emplacements";
	AL["16 Slot"] = "16 emplacements";
	AL["10 Slot"] = "10 emplacements";
	AL["Currency"] = "Monnaie";
	AL["Conjured Item"] = "Objet conjuré";
	AL["Used to summon boss"] = "Utilisé pour invoquer un boss";
	AL["Tradable for sunmote + item above"] = "Echangeable contre une Granule de soleil + l'objet du dessus";
	AL["Card Game Item"] = "Objet du jeu de carte";
	AL["Skill Required:"] = "Compétence requise :";
	AL["Rating:"] = "Côte :"; -- Shorthand for 'Required Rating' for the personal/team ratings
	AL["Random Heroic Reward"] = "Récompense héroique aléatoire";
	--AL["Fishing Daily Reward"] = true; -- à traduire
	--AL["Collector's Edition"] = true; -- à traduire
	--AL["Blizzcon"] = true; -- à traduire
	--AL["WoW Anniversary Celebration"] = true; -- à traduire
	--AL["Daily Reward"] = true; -- à traduire

	-- Minor Labels for loot table descriptions
	AL["Classic WoW"] = "WoW classique";
	--AL["Burning Crusade"] = true;
	--AL["Wrath of the Lich King"] = true;
	AL["Cataclysm"] = "Cataclysme";
	AL["Entrance"] = "Entrée";
	AL["Dungeon Set 1"] = "Set donjon 1";
	AL["Dungeon Set 2"] = "Set donjon 2";
	AL["Dungeon Set 1/2"] = "Set donion 1/2";
	AL["Dungeon Set 3"]  = "Set donjon 3";
	--AL["Tier 1"] = true;
	--AL["Tier 2"] = true;
	--AL["Tier 3"] = true;
	--AL["Tier 4"] = true;
	--AL["Tier 5"] = true;
	--AL["Tier 6"] = true;
	--AL["Tier 7"] = true;
	--AL["Tier 8"] = true;
	--AL["Tier 9"] = true;
	--AL["Tier 10"] = true;
	--AL["Tier 11"] = true;
	AL["10 Man"] = "10 Joueurs";
	AL["10/25 Man"] = "10 / 25 Joueurs";
	AL["Epic Set"] = "Set épique";
	AL["Rare Set"] = "Set supérieur";
	AL["Season 1"] = "Saison 1";
	AL["Season 2"] = "Saison 2";
	AL["Season 3"] = "Saison 3";
	AL["Season 4"] = "Saison 4";
	AL["Season 5"] = "Saison 5";
	AL["Season 6"] = "Saison 6";
	AL["Season 7"] = "Saison 7";
	AL["Season 8"] = "Saison 8";
	AL["Season 9"] = "Saison 9";
	AL["Fire"] = "Feu";
	AL["Water"] = "Eau";
	AL["Wind"] = "Vent";
	AL["Earth"] = "Terre";
	AL["Master Angler"] = "Meilleur pêcheur";
	AL["Fire Resistance Gear"] = "Equipements de Résistance au Feu";
	AL["Arcane Resistance Gear"] = "Equipements de Résistance aux Arcanes";
	AL["Nature Resistance Gear"] = "Equipements de Résistance à la Nature";
	AL["Frost Resistance Gear"] = "Equipements de Résistance au Froid";
	AL["Shadow Resistance Gear"] = "Equipements de Résistance à l'Ombre";
	AL["Classic Sets"] = "Sets classique";

	-- Labels for loot table sections
	AL["Additional Heroic Loot"] = "Loot héroïque additionnel";
	AL["Heroic Mode"] = "Mode Héroïque";
	AL["Normal Mode"] = "Mode Normal";
	--AL["Raid"] = true;
	AL["Hard Mode"] = "Mode difficile";
	AL["Bonus Loot"] = "Bonus de loot";
	AL["Arena Reward"] = "Récompense d'arène";
	AL["Achievement Reward"] = "Récompense des hauts faits";
	--AL["Phase 1"] = true;
	--AL["Phase 2"] = true;
	--AL["Phase 3"] = true;
	AL["First Prize"] = "1er prix";
	AL["Rare Fish Rewards"] = "Récompenses des poissons rares";
	AL["Rare Fish"] = "Poissons rares";
	AL["Heirloom"] = "Héritage";
	AL["Weapons"] = "Armes";
	AL["Accessories"] = "Accessoires";
	AL["Low Level"] = "Bas niveau";
	AL["High Level"] = "Haut niveau";
	--AL["Rare"] = true;

	-- Loot Table Names
	--AL["Level 30-39"] = true;
	--AL["Level 40-49"] = true;
	--AL["Level 50-60"] = true;
	AL["Summon"] = "Invocation";
	AL["Random"] = "Aléatoire";
	AL["Brew of the Month Club"] = "Le club de la Bière du mois";

	-- Cooking descriptions -- à traduire
	--AL["Buff"] = true;
	--AL["Agility"] = true;
	--AL["Intellect"] = true;
	--AL["Strength"] = true;
	--AL["Agility, Intellect, Strength"] = true;
	--AL["Spell Power"] = true;
	--AL["Attack Power"] = true;
	--AL["Spell/Attack Power"] = true;
	--AL["Hit Rating"] = true;
	--AL["Crit Rating"] = true;
	--AL["Crit/Hit Rating"] = true;
	--AL["Haste Rating"] = true;
	--AL["Dodge Rating"] = true;
	--AL["Expertise Rating"] = true;
	--AL["Mastery Rating"] = true;
	--AL["Parry Rating"] = true;
	--AL["Other Ratings"] = true;
	--AL["Resistance"] = true;
	--AL["Health / Second"] = true;
	--AL["Mana / Second"] = true;
	--AL["Tracking"] = true;
	--AL["Emotions"] = true;
	--AL["Alcohol"] = true;
	--AL["Health"] = true;
	--AL["Mana"] = true;
	--AL["Health and Mana"] = true;
	--AL["Other Buffs"] = true;
	--AL["Standard Buffs"] = true;
	--AL["Food without Buffs"] = true;
	--AL["Special"] = true;
	--AL["Feasts"] = true;

	-- Extra Text in Boss lists
	AL["Set: Embrace of the Viper"] = "Set: Etreinte de la vipère";
	AL["Set: Defias Leather"] = "Set: Cuir défias";
	AL["Set: The Gladiator"] = "Set: Le Gladiateur";
	AL["Set: Chain of the Scarlet Crusade"] = "Set: Cotte de mailles de la croisade écarlate";
	AL["Set: The Postmaster"] = "Set: Le Maître de poste";
	AL["Set: Necropile Raiment"] = "Set: Grande tenue nécropile";
	AL["Set: Cadaverous Garb"] = "Set: Atours cadavériques";
	AL["Set: Bloodmail Regalia"] = "Set: Tenue de parade en mailles sanglantes";
	AL["Set: Deathbone Guardian"] = "Set: Gardien des ossements";
	AL["Set: Dal'Rend's Arms"] = "Set: Armes de Dal'Rend";
	AL["Set: Spider's Kiss"] = "Baiser de l'araignée";
	AL["AQ20 Class Sets"] = "Sets de Classe AQ20";
	AL["AQ Enchants"] = "Enchantements AQ";
	AL["AQ40 Class Sets"] = "Sets de Classe AQ40";
	AL["AQ Opening Quest Chain"] = "Quêtes d'ouverture d'AQ";
	AL["ZG Class Sets"] = "Sets de Classe ZG";
	AL["ZG Enchants"] = "Enchantements ZG";
	AL["Class Books"] = "Livres de classe";
	AL["Tribute Run"] = "Tribut du Roi";
	AL["Dire Maul Books"] = "Livres de Hache Tripes";
	AL["Random Boss Loot"] = "Objets aléatoires des boss";
	AL["BT Patterns/Plans"] = "Patrons / Plans du Temple Noir";
	AL["Hyjal Summit Designs"] = "Dessins du Sommet d'Hyjal";
	AL["SP Patterns/Plans"] = "Patrons / Plans du Plateau du Puits de soleil";
	AL["Ulduar Formula/Patterns/Plans"] = "Formules / Patrons / Plans d'Ulduar";
	AL["Trial of the Crusader Patterns/Plans"] = "Patrons / Plans de L'épreuve du croisé";
	--AL["BRD Blacksmithing Plans"] = true; -- à traduire

	-- General titles
	AL["Achievement"] = "Haut fait";
	AL["Promotional & Card Game"] = "Promotionnel & Jeu de cartes";

	-- Companions
	AL["Achievement & Faction Reward Companions"] = "Haut fait & mascottes de récompenses de factions";
	AL["Achievement & Faction Reward"] = "Haut fait & récompense de faction";
	AL["Card Game Companions"] = "Mascottes des jeux de cartes";
	AL["Companion Accessories"] = "Accessoires pour mascottes";
	AL["Companion Store"] = "Mascottes de la boutique Blizzard";
	AL["Crafted Companions"] = "Mascottes de l'artisanat";
	AL["Dungeon/Raid"] = "Donjon / Raid";
	--AL["Faction"] = true;
	AL["Merchant Sold Companions"] = "Mascottes des marchands";
	AL["Pets"] = "Animaux de compagnie";
	AL["Promotional Companions"] = "Mascottes promotionnelles";
	AL["Quest Reward Companions"] = "Mascottes des récompenses de quêtes";
	AL["Rare Companions"] = "Mascottes rares";
	AL["Unobtainable Companions"] = "Mascottes impossible à obtenir";

	-- Mounts
	AL["Alliance Flying Mounts"] = "Montures volantes de l'Alliance";
	AL["Alliance Mounts"] = "Montures de l'Alliance";
	AL["Horde Flying Mounts"] = "Montures volantes de la Horde";
	AL["Horde Mounts"] = "Montures de la Horde";
	AL["Card Game Mounts"] = "Montures du jeu de cartes";
	AL["Crafted Mounts"] = "Montures frabiquées";
	AL["Event Mounts"] = "Montures d'événements";
	AL["Neutral Faction Mounts"] = "Montures de factions neutres";
	AL["PvP Mounts"] = "Montures JcJ";
	AL["Alliance PvP Mounts"] = "Montures JcJ de l'Alliance";
	AL["Horde PvP Mounts"] = "Montures JcJ de la Horde";
	AL["Halaa PvP Mounts"] = "Montures JcJ de Halaa";
	AL["Promotional Mounts"] = "Montures promotionnelles";
	AL["Rare Mounts"] = "Montures rares";
	--AL["Unobtainable Mounts"] = true;

	-- Tabards
	AL["Achievement & Quest Reward Tabards"] = true;
	AL["Alliance Tabards"] = true;
	AL["Card Game Tabards"] = true;
	AL["Horde Tabards"] = true;
	AL["Neutral Faction Tabards"] = true;
	AL["PvP Tabards"] = true;
	AL["Unobtainable Tabards"] = true;

	-- Darkmoon Faire
	AL["Darkmoon Faire Rewards"] = "Récompenses Foire de Sombrelune";
	AL["Low Level Decks"] = "Cartes bas level";
	--AL["Level 60 Trinkets"] = true;
	--AL["Level 70 Trinkets"] = true;
	--AL["Level 60 & 70 Trinkets"] = true;
	--AL["Level 80 Trinkets"] = true;
	--AL["Level 85 Trinkets"] = true;

	-- Card Game Decks and descriptions
	AL["Loot Card Items"] = "Objets des cartes à jouer";
	AL["UDE Items"] = "Objets (points UDE)";

	-- First set
	AL["Heroes of Azeroth"] = "Héros d'Azeroth";
	AL["Landro Longshot"] = "Landro Tirauloin";
	AL["Thunderhead Hippogryph"] = "Hippogryffe Tête-Tonnerre";
	AL["Saltwater Snapjaw"] = "Gueule d'acier des mers";

	-- Second set
	AL["Through The Dark Portal"] = "A Travers la Porte des Ténèbres";
	AL["King Mukla"] = "Roi Mukla";
	AL["Rest and Relaxation"] = "Repos et relaxation";
	AL["Fortune Telling"] = "La Bonne Aventure";

	-- Third set
	AL["Fires of Outland"] = "Les Feux de l'Outreterre";
	AL["Spectral Tiger"] = "Tigre Spectral";
	AL["Gone Fishin'"] = "Parti Pêcher";
	AL["Goblin Gumbo"] = "Gumbo Gobelin";

	-- Fourth set
	AL["March of the Legion"] = "Marche de la Légion";
	--AL["Kiting"] = true;
	AL["Robotic Homing Chicken"] = "Poulet Robot Guidé";
	AL["Paper Airplane"] = "Machine volante en papier";

	-- Fifth set
	AL["Servants of the Betrayer"] = "Les Serviteurs du Traître";
	AL["X-51 Nether-Rocket"] = "Fusée-de-néant X-51";
	AL["Personal Weather Machine"] = "Machine météorologique gobeline";
	AL["Papa Hummel's Old-fashioned Pet Biscuit"] = "Biscuit pour familier à l'ancienne de papa Humme";

	-- Sixth set -- à traduire
	AL["Hunt for Illidan"] = "La Traque d'Illidan";
	--AL["The Footsteps of Illidan"] = true;
	--AL["Disco Inferno!"] = true;
	AL["Ethereal Plunderer"] = "Pilleur éthérien";

	-- Seventh set -- à traduire
	AL["Drums of War"] = "Tambours de Guerre";
	--AL["The Red Bearon"] = true;
	--AL["Owned!"] = true;
	--AL["Slashdance"] = true;

	-- Eighth set
	AL["Blood of Gladiators"] = "Le Sang des Gladiateurs";
	AL["Sandbox Tiger"] = "Tigre de bac à sable";
	AL["Center of Attention"] = "Chemise violette épique";
	AL["Foam Sword Rack"] = "Râtelier d'épées en mousse";

	-- Ninth set -- à traduire
	--AL["Fields of Honor"] = true;
	--AL["Path of Cenarius"] = true;
	--AL["Pinata"] = true;
	--AL["El Pollo Grande"] = true;

	-- Tenth set -- à traduire
	--AL["Scourgewar"] = true;
	--AL["Tiny"] = true;
	--AL["Tuskarr Kite"] = true;
	--AL["Spectral Kitten"] = true;

	-- Eleventh set -- à traduire
	--AL["Wrathgate"] = true;
	--AL["Statue Generator"] = true;
	--AL["Landro's Gift"] = true;
	--AL["Blazing Hippogryph"] = true;

	-- Twelvth set -- à traduire
	--AL["Icecrown"] = true;
	--AL["Wooly White Rhino"] = true;
	--AL["Ethereal Portal"] = true;
	--AL["Paint Bomb"] = true;

	-- Thirtheenth set -- à traduire
	--AL["Worldbreaker"] = true;

	-- Battleground Brackets
	AL["Old PvP Rewards"] = "Anciennes récompenses JcJ";
	AL["BG/Open PvP Rewards"] = "CdB / Récompenses JcJ mondial";
	AL["Misc. Rewards"] = "Récompenses diverses";
	AL["Level 10-19 Rewards"] = "Récompenses niveau 10-19";
	AL["Level 20-39 Rewards"] = "Récompenses niveau 20-39";
	AL["Level 20-29 Rewards"] = "Récompenses niveau 20-29";
	AL["Level 30-39 Rewards"] = "Récompenses niveau 30-39";
	AL["Level 40-49 Rewards"] = "Récompenses niveau 40-49";
	AL["Level 50-59 Rewards"] = "Récompenses niveau 50-59";
	AL["Level 60 Rewards"] = "Récompenses niveau 60";

	-- Brood of Nozdormu Paths
	AL["Path of the Conqueror"] = "La voie du conquérant";
	AL["Path of the Invoker"] = "La voie de l'invocateur";
	AL["Path of the Protector"] = "La voie du protecteur";

	-- Violet Eye Paths
	AL["Path of the Violet Protector"] = "La voie du protecteur pourpre";
	AL["Path of the Violet Mage"] = "La voie du mage pourpre";
	AL["Path of the Violet Assassin"] = "La voie de l'assassin pourpre";
	AL["Path of the Violet Restorer"] = "La voie du guérisseur pourpre";

	-- Ashen Verdict Paths
	AL["Path of Courage"] = "La voie du courage";
	AL["Path of Destruction"] = "La voie de la destruction";
	AL["Path of Vengeance"] = "La voie de la vengeance";
	AL["Path of Wisdom"] = "La voie de la sagesse";

	-- AQ Opening Event
	AL["Red Scepter Shard"] = "Fragment de sceptre rouge";
	AL["Blue Scepter Shard"] = "Fragment de sceptre bleu";
	AL["Green Scepter Shard"] = "Fragment de sceptre vert";
	AL["Scepter of the Shifting Sands"] = "Le Sceptre des Sables changeants";

	-- World PvP
	AL["Hellfire Fortifications"] = "Fortifications des flammes infernales";
	AL["Twin Spire Ruins"] = "Ruines des flèches jumelles";
	AL["Spirit Towers"] = "Tour des esprits";
	--AL["Halaa"] = true,
	AL["Venture Bay"] = "Baie de la KapitalRisk";

	-- Karazhan Opera Event Headings
	AL["Shared Drops"] = "Objets en commun";
	AL["Wizard of Oz"] = "Le Magicien d'Oz";
	AL["Red Riding Hood"] = "Petit Chaperon Rouge";

	-- Karazhan Animal Boss Types
	AL["Spider"] = "Araignée";
	AL["Darkhound"] = "Sombredogue";
	AL["Bat"] = "Chauve-souris";

	-- ZG Tokens
	AL["Primal Hakkari Kossack"] = "Casaque primordiale hakkari";
	AL["Primal Hakkari Shawl"] = "Châle primordial hakkari";
	AL["Primal Hakkari Bindings"] = "Manchettes primordiales hakkari";
	AL["Primal Hakkari Sash"] = "Echarpe primordiale hakkari";
	AL["Primal Hakkari Stanchion"] = "Etançon primordial hakkari";
	AL["Primal Hakkari Aegis"] = "Egide primordiale hakkari";
	AL["Primal Hakkari Girdle"] = "Ceinturon primordial hakkari";
	AL["Primal Hakkari Armsplint"] = "Brachiales primordiales hakkari";
	AL["Primal Hakkari Tabard"] = "Tabard primordial hakkari";

	-- AQ20 Tokens
	AL["Qiraji Ornate Hilt"] = "Manche orné qiraji";
	AL["Qiraji Martial Drape"] = "Drapé martial qiraji";
	AL["Qiraji Magisterial Ring"] = "Anneau de magistrat qiraji";
	AL["Qiraji Ceremonial Ring"] = "Anneau de cérémonie qiraji";
	AL["Qiraji Regal Drape"] = "Drapé royal qiraji";
	AL["Qiraji Spiked Hilt"] = "Manche à pointes qiraji";

	-- AQ40 Tokens
	AL["Qiraji Bindings of Dominance"] = "Manchettes de domination qiraji";
	AL["Qiraji Bindings of Command"] = "Diadème de Vek'nilash";
	AL["Vek'nilash's Circlet"] = "Peau intacte d'Ouro";
	AL["Vek'lor's Diadem"] = "Carcasse du Dieu très ancien";
	AL["Ouro's Intact Hide"] = "Manchettes de commandement qiraji";
	AL["Skin of the Great Sandworm"] = "Diadème de Vek'lor";
	AL["Husk of the Old God"] = "Peau du Grand ver des sables";
	AL["Carapace of the Old God"] = "Carapace du Dieu très ancien";

	-- Classic WoW Sets
	AL["Zul'Gurub Rings"] = "Anneaux Zul'Gurub";


	-- Recipe origin strings
	AL["Trainer"] = "Entraineur";
	AL["Discovery"] = "Découverte";
	AL["World Drop"] = "Drop mondial";
	--AL["Drop"] = true;
	AL["Vendor"] = "Vendeur";
	AL["Crafted"] = "Créer";

	-- Level 80 PvP Weapons
	AL["Wrathful Gladiator\'s Weapons"] = "Armes du gladiateur courroucé";

	-- Months
	AL["January"] = "Janvier";
	AL["February"] = "Février";
	AL["March"] = "Mars";
	AL["April"] = "Avril";
	AL["May"] = "Mai";
	AL["June"] = "Juin";
	AL["July"] = "Juillet";
	AL["August"] = "Août";
	AL["September"] = "Septembre";
	AL["October"] = "Octobre";
	AL["November"] = "Novembre";
	AL["December"] = "Décembre";

	-- Specs
	AL["Balance"] = "Equilibre";
	AL["Feral"] = "Combat farouche";
	AL["Restoration"] = "Restauration";
	AL["Holy"] = "Sacré";
	--AL["Discipline"] = true;
	--AL["Protection"] = true;
	AL["Retribution"] = "Vindicte";
	AL["Shadow"] = "Ombre";
	AL["Elemental"] = "Elémentaire";
	AL["Enhancement"] = "Amélioration";
	AL["Fury"] = "Fureur";
	AL["Demonology"] = "Démonologie";
	--AL["Destruction"] = true;
	--AL["Tanking"] = true;
	--AL["DPS"] = true;

	-- Naxx Zones
	AL["Construct Quarter"] = "Le quartier des Assemblages";
	AL["Arachnid Quarter"] = "Le quartier des Arachnides";
	AL["Military Quarter"] = "Le quartier Militaire";
	AL["Plague Quarter"] = "Le quartier de la Peste";
	AL["Frostwyrm Lair"] = "Repaire de la Wyrm des glaces";

	-- NPCs missing from BabbleBoss
	--AL["Trash Mobs"] = true,
	AL["Dungeon Set 2 Summonable"] = "Invocation Set Donjon 2";
	--AL["Theldren"] = true,
	AL["Sothos and Jarien"] = "Sothos et Jarien";
	AL["Druid of the Fang"] = "Druide du Croc";
	AL["Defias Strip Miner"] = "Carrier défias";
	AL["Defias Overseer/Taskmaster"] = "Sous-chef/Surveillant défias";
	AL["Scarlet Defender/Myrmidon"] = "Défenseur/Myrmidon écarlate";
	AL["Scarlet Champion"] = "Champion écarlate";
	AL["Scarlet Centurion"] = "Centurion écarlate";
	AL["Scarlet Trainee"] = "Jeune recrue écarlate";
	--AL["Herod/Mograine"] = true,
	AL["Scarlet Protector/Guardsman"] = "Protecteur/Gardien écarlate";
	AL["Shadowforge Flame Keeper"] = "Gardien des flammes Ombreforge";
	AL["Avatar of the Martyred"] = "Avatar des martyrs";
	AL["Nexus Stalker"] = "Traqueur du nexus";
	AL["Auchenai Monk"] = "Moine auchenaï";
	AL["Cabal Fanatic"] = "Fanatique de la Cabale";
	AL["Unchained Doombringer"] = "Porte-destin sans chaîne";
	AL["Crimson Sorcerer"] = "Ensorceleur cramoisi";
	AL["Thuzadin Shadowcaster"] = "Exhalombre Thuzadin";
	AL["Crimson Inquisitor"] = "Inquisiteur cramoisi";
	AL["Crimson Battle Mage"] = "Mage de bataille cramoisi";
	AL["Ghoul Ravener"] = "Goule vorace";
	AL["Spectral Citizen"] = "Citoyen spectral";
	AL["Spectral Researcher"] = "Chercheur spectral";
	AL["Scholomance Adept"] = "Adepte de la Scholomance";
	AL["Scholomance Dark Summoner"] = "Invocateur des ténèbres de la Scholomance";
	AL["Blackhand Elite"] = "Elite Main-noire";
	AL["Blackhand Assassin"] = "Assassin Main-noire";
	AL["Firebrand Pyromancer"] = "Pyromancien de Brandefeu";
	AL["Firebrand Invoker"] = "Invocateur de Brandefeu";
	AL["Firebrand Grunt"] = "Grunt de Brandefeu";
	AL["Firebrand Legionnaire"] = "Légionnaire de Brandefeu";
	AL["Spirestone Warlord"] = "Chef de guerre Pierre-du-pic";
	AL["Spirestone Mystic"] = "Mystique Pierre-du-pic";
	AL["Anvilrage Captain"] = "Capitaine Ragenclume";
	AL["Anvilrage Marshal"] = "Maréchal Ragenclume";
	AL["Doomforge Arcanasmith"] = "Forgeron des arcanes Forge-ruine";
	AL["Weapon Technician"] = "Ingénieur de siège";
	AL["Doomforge Craftsman"] = "Artisan Forge-ruine";
	AL["Murk Worm"] = "Ver des boues";
	AL["Atal'ai Witch Doctor"] = "Sorcier-docteur atal'ai";
	AL["Raging Skeleton"] = "Squelette déchaîné";
	AL["Ethereal Priest"] = "Prêtre éthérien";
	AL["Sethekk Ravenguard"] = "Garde-corbeau Sethekk";
	AL["Time-Lost Shadowmage"] = "Ombremage du Temps-perdu";
	AL["Coilfang Sorceress"] = "Sorcière de Glissecroc";
	AL["Coilfang Oracle"] = "Oracle de Glissecroc";
	AL["Shattered Hand Centurion"] = "Centurion de la Main brisée";
	AL["Eredar Deathbringer"] = "Porte-mort érédar";
	AL["Arcatraz Sentinel"] = "Sentinelle de l'Arcatraz";
	AL["Gargantuan Abyssal"] = "Abyssal gargantuesque";
	AL["Sunseeker Botanist"] = "Botaniste Cherche-soleil";
	AL["Sunseeker Astromage"] = "Astromage Cherche-soleil";
	AL["Durnholde Rifleman"] = "Fusilier de Fort-de-Durn";
	AL["Rift Keeper/Rift Lord"] = "Gardien des failles/Seigneur des failles";
	AL["Crimson Templar"] = "Templier cramoisi";
	AL["Azure Templar"] = "Templier d'azur";
	AL["Hoary Templar"] = "Templier chenu";
	AL["Earthen Templar"] = "Templier terrestre";
	AL["The Duke of Cynders"] = "Le duc des Cendres";
	AL["The Duke of Fathoms"] = "Le duc des Profondeurs";
	AL["The Duke of Zephyrs"] = "Le duc des Zéphyrs";
	AL["The Duke of Shards"] = "Le duc des Eclats";
	AL["Aether-tech Assistant"] = "Techno-éther assistant";
	AL["Aether-tech Adept"] = "Techno-éther adepte";
	AL["Aether-tech Master"] = "Techno-éther apprenti";
	AL["Trelopades"] = "Trelopades";
	AL["King Dorfbruiser"] = "Roi Cognenabot";
	AL["Gorgolon the All-seeing"] = "Gorgolon l'Omnivoyant";
	AL["Matron Li-sahar"] = "Matrone Li-sahar";
	AL["Solus the Eternal"] = "Solus l'Éternel";
	AL["Smokywood Pastures Vendor"] = "Vendeurs de Gourmandises Fumebois";
	--AL["Shartuul"] = true,
	AL["Darkscreecher Akkarai"] = "Akkarai le Hurle-sombre";
	--AL["Karrog"] = true,
	AL["Gezzarak the Huntress"] = "Gezzarak la Chasseresse";
	AL["Vakkiz the Windrager"] = "Vakkiz le Ragevent";
	--AL["Terokk"] = true,
	AL["Armbreaker Huffaz"] = "Casse-bras Huffaz";
	AL["Fel Tinkerer Zortan"] = "Bricoleur gangrené Zortan";
	--AL["Forgosh"] = true,
	--AL["Gul'bor"] = true,
	AL["Malevus the Mad"] = "Malevus le Fol";
	AL["Porfus the Gem Gorger"] = "Porfus le Goinfre-gemmes";
	AL["Wrathbringer Laz-tarash"] = "Porte-courroux Laz-tarash";
	AL["Bash'ir Landing Stasis Chambers"] = "Chambre de stase alpha du point d'ancrage de Bash'ir";
	AL["Templars"] = "Templiers";
	AL["Dukes"] = "Ducs";
	AL["High Council"] = "Princes";
	AL["Barleybrew Brewery"] = "Apprenti Brasselorge";
	AL["Thunderbrew Brewery"] = "Apprenti Tonnebière";
	AL["Gordok Brewery"] = "Apprenti de la bière gordok";
	AL["Drohn's Distillery"] = "Apprenti de la distillerie Drohn";
	AL["T'chali's Voodoo Brewery"] = "Apprenti de la brasserie vaudou de T'chali";
	AL["Scarshield Quartermaster"] = "Intendant du Bouclier balafré";
	AL["Father Flame"] = "Père des flammes";
	--AL["Thomas Yance"] = true,
	AL["Knot Thimblejack"] = "Noué Dédodevie";
	AL["Shen'dralar Provisioner"] = "Approvisionneur Shen'dralar";
	AL["Namdo Bizzfizzle"] = "Namdo Ventaperte";
	AL["The Nameles Prophet"] = "Le Prophète sans nom";
	AL["Rajaxx's Captains"] = "Les Capitaines de Rajaxx";
	AL["Razorfen Spearhide"] = "Lanceur de Tranchebauge";
	AL["Kalldan Felmoon"] = "Kalldan Gangrelune";
	AL["Magregan Deepshadow"] = "Magregan Fondombre";
	--AL["Don Carlos"] = true,
	--AL["Thomas Yance"] = true;
	AL["Aged Dalaran Wizard"] = "Sorcier de Dalaran âgé";
	AL["Felsteed"] = "Palefroi corrompu";
	AL["Shattered Hand Executioner"] = "Bourreau de la Main brisée";
	AL["Time-Lost Proto Drake"] = "Rênes de proto-drake perdu dans le temps";
	AL["Razzashi Raptor"] = "Raptor Razzashi";
	AL["Deviate Ravager/Deviate Guardian"] = "Ravageur déviant/Gardien déviant";
	--AL["Servant's Quarter Animal Bosses"] = true; -- à traduire
	AL["Jadefang"] = "Jadecroc";
	--AL["Aeonaxx"] = true; -- à traduire
	--AL["Prince Sarsarun"] = true;
	-- AL["Highlord Kruul"] = true; -- added until decided if the set gets removed -- à traduire

	-- Zones
	--AL["World Drop"] = true,
	AL["Trial of the Grand Crusader"] = "L'épreuve du grand croisé";
	AL["Crusader's Square"] = "Place des Croisés";
	--AL["The Gauntlet"] = true; -- à traduire

	-- Shortcuts for Bossname files
	--AL["LBRS"] = true,
	--AL["UBRS"] = true,
	AL["CoT1"] = "GDT1";
	AL["CoT2"] = "GDT2";
	--AL["Scholo"] = true,
	--AL["Strat"] = true,
	AL["Serpentshrine"] = "SCC";
	--AL["Avatar"] = true; -- Avatar of the Martyred

	-- Chests, etc
	--AL["Ring of Law"] = true;
	--AL["Monument of Franclorn Forgewright"] = true;
	--AL["The Grim Guzzler"] = true;
	--AL["Summoner's Tomb"] = true;
	AL["The Secret Safe"] = "Coffre à relique";
	AL["The Vault"] = "La Chambre forte";
	AL["Ogre Tannin Basket"] = "Panier Ogre de tannin";
	AL["Fengus's Chest"] = "Coffre de Fengus";
	AL["The Prince's Chest"] = "Coffre du Prince";
	AL["Doan's Strongbox"] = "Coffre de Doan";
	AL["Frostwhisper's Embalming Fluid"] = "Liquide d'embaumement de Murmegivre";
	AL["Unforged Rune Covered Breastplate"] = "Plastron couvert de runes inachevé";
	AL["Malor's Strongbox"] = "Coffre de Foi";
	AL["Unfinished Painting"] = "Toile inachevée";
	AL["Felvine Shard"] = "Fragment de la Gangrevigne";
	AL["Baelog's Chest"] = "Coffre de Baelog";
	AL["Lorgalis Manuscript"] = "Manuscrit de Lorgalis";
	AL["Fathom Core"] = "Noyau de la Brasse";
	AL["Conspicuous Urn"] = "Urne ostentatoire";
	AL["Gift of Adoration"] = "Cadeau d'adoration";
	AL["Box of Chocolates"] = "Boîte de chocolats";
	AL["Treat Bag"] = "Sac de friandises";
	AL["Gaily Wrapped Present"] = "Cadeau à l'emballage multicolore";
	AL["Festive Gift"] = "Cadeau de fête";
	AL["Ticking Present"] = "Cadeau tic-taquant";
	AL["Gently Shaken Gift"] = "Cadeau secoué doucement";
	AL["Carefully Wrapped Present"] = "Biscuit du Voile d'hiver";
	AL["Winter Veil Gift"] = "Rob-fusée mécanique";
	AL["Smokywood Pastures Extra-Special Gift"] = "Cadeau extra-spécial des Gourmandises Fumebois";
	AL["Brightly Colored Egg"] = "Oeuf brillamment coloré";
	AL["Lunar Festival Fireworks Pack"] = "Sac de feux d'artifice de la fête lunaire";
	AL["Lucky Red Envelope"] = "Enveloppe rouge porte-bonheur";
	AL["Small Rocket Recipes"] = "Recettes des petites comètes";
	AL["Large Rocket Recipes"] = "Recettes de grandes comètes";
	AL["Cluster Rocket Recipes"] = "Recettes de chapelet de comètes";
	AL["Large Cluster Rocket Recipes"] = "Recettes de chapelet de grandes comètes";
	AL["Timed Reward Chest"] = "Coffre du parcours rapide";
	AL["Timed Reward Chest 1"] = "Coffre du parcours rapide 1";
	AL["Timed Reward Chest 2"] = "Coffre du parcours rapide 2";
	AL["Timed Reward Chest 3"] = "Coffre du parcours rapide 3";
	AL["Timed Reward Chest 4"] = "Coffre du parcours rapide 4";
	AL["The Talon King's Coffer"] = "Le coffre du roi-serre";
	AL["Krom Stoutarm's Chest"] = "Coffre de Krom Rudebras";
	AL["Garrett Family Chest"] = "Coffre de la famille Garrett";
	AL["Reinforced Fel Iron Chest"] = "Coffre en gangrefer renforcé";
	AL["DM North Tribute Chest"] = "Coffre du Roi (HT Nord)";
	AL["The Saga of Terokk"] = "La Saga de Terokk";
	AL["First Fragment Guardian"] = "Gardien du premier fragment";
	AL["Second Fragment Guardian"] = "Gardien du second fragment";
	AL["Third Fragment Guardian"] = "Gardien du troisième fragment";
	AL["Overcharged Manacell"] = "Cellule de mana surchargée";
	AL["Mysterious Egg"] = "Oeuf mystérieux";
	AL["Hyldnir Spoils"] = "Butin hyldnir";
	AL["Ripe Disgusting Jar"] = "Jarre dégoûtante mûre";
	AL["Cracked Egg"] = "Oeuf brisé";
	AL["Small Spice Bag"] = "Petit sac d'épices";
	AL["Handful of Candy"] = "Poignée de bonbons";
	AL["Lovely Dress Box"] = "Boîte de robe ravissante";
	AL["Dinner Suit Box"] = "Boîte d'habit de soirée";
	AL["Bag of Heart Candies"] = "Sachet de bonbons en forme de cœur";
	--AL["Hidden Stash"] = true; -- à traduire

	-- Error Messages and warnings
	AL["AtlasLoot Error!"] = "Erreur AtlasLoot !";
	AL["WishList Full!"] = "Liste de souhaits complète !";
    	AL["No match found for"] = "Aucun résultat trouvé pour";
	AL[" is safe."] = " est valide.";
	AL["Server queried for "] = "Interrogation du serveur pour ";
	AL[".  Right click on any other item to refresh the loot page."] = ".  Clic-Droit sur un autre objet permet de rafraîchir la page.";

	-- Incomplete Table Registry error message
	AL[" not listed in loot table registry, please report this message to the AtlasLoot forums at http://www.atlasloot.net"] = " non répertorié dans la table des objets enregistrés, merci de transmettre ce message sur les forums d'AtlasLoot sur http://www.atlasloot.net";

	-- LoD Module disabled or missing
	AL[" is unavailable, the following load on demand module is required: "] = " est indisponible, le module suivant (chargé à la demande) est requis : ";

	-- LoD Module load sequence could not be completed
	AL["Status of the following module could not be determined: "] = "Le status du module suivant n'a pu être déterminé : ";

	-- LoD Module required has loaded, but loot table is missing
	AL[" could not be accessed, the following module may be out of date: "] = " n'a pas pu être consulté, le module suivant peut être dépassé : ";

	-- LoD module not defined
	AL["Loot module returned as nil!"] = "Le module de loot a retourné une erreur !";

	-- LoD module loaded successfully
	AL["sucessfully loaded."] = "chargement réussi.";

	-- Need a big dataset for searching
	AL["Loading available tables for searching"] = "Chargement des tables disponibles pour la recherche";

 	-- All Available modules loaded
	AL["All Available Modules Loaded"] = "Tous les modules disponibles sont chargés.";

	-- First time user
	AL["Welcome to Atlasloot Enhanced.  Please take a moment to set your preferences."] = "Bienvenue dans AtlasLoot Enhanced. Veuillez prendre un moment pour définir vos préférences.";
	AL["Welcome to Atlasloot Enhanced.  Please take a moment to set your preferences for tooltips and links in the chat window.\n\n  This options screen can be reached again at any later time by typing '/atlasloot'."] = "Bienvenue dans AtlasLoot Enhaced. S'il vous plaît, prenez un moment pour définir vos préférences pour les info-bulles et les liens dans la fenêtre de chat.\n\nLes options peuvent être activées à tout moment en tapant '/atlasloot'.";
	AL["Setup"] = "Installation";

	-- Old Atlas Detected
	AL["It has been detected that your version of Atlas does not match the version that Atlasloot is tuned for ("] = "Il a été détecté que votre version d'Atlas n'est pas adapté à la version d'AtlasLoot, laquelle est étudiée pour (";
	AL[").  Depending on changes, there may be the occasional error, so please visit http://www.atlasmod.com as soon as possible to update."] = "). Suivant les changements, des erreurs peuvent survenir, vous pouvez consulter le site http://www.atlasmod.com/ pour les futures mises à jour.";
	--AL["OK"] = true,
	AL["Incompatible Atlas Detected"] = "Incompatibilité d'Atlas détectée";

	-- Unsafe item tooltip
	AL["Unsafe Item"] = "Objet invalide";
	AL["This item is not available on your server or your battlegroup yet."] = "Cet objet n'est pas encore disponible sur votre serveur ou sur votre champ de bataille";
	AL["You can right-click to attempt to query the server.  You may be disconnected."] = "Un Clic-Droit permet de tenter d'interroger le serveur.\nVous pouvez être déconnecté.";
end