local media = LibStub("LibSharedMedia-3.0")
media:Register("font", "Anime Ace",				[[Interface\Addons\Fontain\fonts\animeace.ttf]])
media:Register("font", "Chinese",				[[Interface\Addons\Fontain\fonts\CHINESETAKEAWAY.ttf]])
media:Register("font", "Ikarus",				[[Interface\Addons\Fontain\fonts\IKARRG__.TTF]])
media:Register("font", "JJ Stencil",			[[Interface\Addons\Fontain\fonts\JJSTS___.TTF]])
media:Register("font", "June Gull",				[[Interface\Addons\Fontain\fonts\junegull.ttf]])
media:Register("font", "Parry Hotter",			[[Interface\Addons\Fontain\fonts\ParryHotter.ttf]])
media:Register("font", "Rebuffed",				[[Interface\Addons\Fontain\fonts\REBUFFED.TTF]])
media:Register("font", "Calibri V1",			[[Interface\Addons\Fontain\fonts\Calibri1.ttf]])